### ISSUE TITLE
How to pass data to component?

### ISSUE THREAD

**Issue by gapipro** [vueui/vue-ui#2]
So if I put checkbox on my page and I wish to update data based on checkbox state, how do I do that?

parent data:

``` javascript
{
  'marked':false
}
```

When user enables checkbox `marked` should change to `true` and vice versa.

**Comment by agonbina** [comment]
I think this might be an issue with the Vue.js version you are using. When I started this project the way a child component was resolved(ie transcluded) was different compared to starting since Vue 0.11 (I belive)

**Comment by gapipro** [comment]
Yea, I experimented a bit with latest Vue version 0.11.5 and I managed to link data to component with some modifications.
