### ISSUE TITLE
Will you be updating to make this package compatiable with Vue.JS 1.x?

### ISSUE THREAD

**Issue by kharysharpe** [vueui/vue-ui#4]
This is a great project, please consider updating it.

**Comment by agonbina** [comment]
@kharysharpe as much as I'd love to work with Vue and make this library compatible with 1.x, unfortunately I've moved away from using Vue.js and don't have any immediate plans to update this library anytime soon. I'm currently spending all of my time working with React, but that is not to say I don't like Vue as a library, but we're using React at my workplace so my time to work on anything unrelated to React is quite limited
